/* This file generated by ChatGPT, mostly based on my code.
 * So it's public domain!
 * */

#pragma once

#include <cassert>
#include <vector>

#include "int.h"
#include "setbits.h"

template<
    u32 dirty_shift,
    u32 total_bytes,
    u32 block_align_shift,
    typename block_t,
    typename second_block_t = void
>
struct block_cache_vector;

template<u32 dirty_shift, u32 total_bytes, u32 block_align_shift, typename block_t>
struct block_cache_vector<dirty_shift, total_bytes, block_align_shift, block_t, void> {
    static constexpr u32 block_align = 1u << block_align_shift;
    static constexpr u32 block_align_mask = block_align - 1;

    using dirty_t = dirty_bit_filter<dirty_shift, total_bytes>;

    dirty_t dirty{};
    std::vector<block_t> store{};

    block_cache_vector() {
        store.resize(total_bytes >> block_align_shift);

        for (u32 i = 0; i < store.size(); i++) {
            store[i].cached_addr = i << block_align_shift;
        }
    }
    static constexpr u32 align_block_addr_down(u32 addr) {
        return addr & ~block_align_mask;
    }

    static constexpr u32 align_block_addr_up(u32 addr) {
        return (addr + block_align - 1) & ~block_align_mask;
    }

    u32 index_for_addr(u32 cached_addr) const {
        return cached_addr >> block_align_shift;
    }

    template<u32 store_num = 0>
    auto *peek_block(u32 cached_addr) {
        static_assert(store_num == 0);
        return &store[index_for_addr(cached_addr)];
    }

    template<u32 store_num = 0>
    const auto *peek_block(u32 cached_addr) const {
        static_assert(store_num == 0);
        return &store[index_for_addr(cached_addr)];
    }

    template<u32 store_num = 0>
    auto *get_block(u32 cached_addr, u32 max_block_bytes) {
        static_assert(store_num == 0);

        auto *block = peek_block<0>(cached_addr);

        if (!block->instructions.empty()) {
            invalidate_if_dirty(block->cached_addr, block->cached_addr + block->sz, max_block_bytes);
        }

        return block;
    }

    void reset_dirty() {
        dirty.reset();
    }

    void clear_all_blocks() {
        for (auto &block : store) block.instructions.clear();
    }

    void reset() {
        reset_dirty();
        clear_all_blocks();
    }

    void mark_dirty(u32 cached_addr) {
        dirty.set(cached_addr);
    }

    void mark_dirty_range(u32 cached_start, u32 cached_end_exclusive) {
        dirty.set_range(cached_start, cached_end_exclusive);
    }

    bool has_dirty_in_range(u32 cached_start, u32 cached_end_exclusive) const {
        return dirty.test_range_byte(cached_start, cached_end_exclusive);
    }

    void clear_dirty_range(u32 cached_start, u32 cached_end_exclusive) {
        dirty.clear_range(cached_start, cached_end_exclusive);
    }

    template<typename vec_t>
    static void invalidate_store(vec_t &target_store, u32 cached_start, u32 cached_end_exclusive, u32 first_index, u32 end_index_exclusive) {
        for (u32 i = first_index; i < end_index_exclusive; i++) {
            auto &candidate = target_store[i];

            if (candidate.instructions.empty()) continue;

            const u32 candidate_start = candidate.cached_addr;
            const u32 candidate_end_exclusive = candidate.cached_addr + candidate.sz;

            if (candidate_start < cached_end_exclusive && candidate_end_exclusive > cached_start) {
                candidate.instructions.clear();
            }
        }
    }

    void invalidate_overlapping_blocks(u32 cached_start, u32 cached_end_exclusive, u32 max_block_bytes) {
        u32 scan_start = cached_start > max_block_bytes ? cached_start - max_block_bytes : 0;
        scan_start = align_block_addr_down(scan_start);

        u32 scan_end_exclusive = align_block_addr_up(cached_end_exclusive);
        if (scan_end_exclusive > total_bytes) scan_end_exclusive = total_bytes;

        const u32 first_index = scan_start >> block_align_shift;
        const u32 end_index_exclusive = scan_end_exclusive >> block_align_shift;

        invalidate_store(store, cached_start, cached_end_exclusive, first_index, end_index_exclusive);
    }

    void invalidate_if_dirty(u32 block_cached_start, u32 block_cached_end_exclusive, u32 max_block_bytes) {
        if (!has_dirty_in_range(block_cached_start, block_cached_end_exclusive)) return;

        invalidate_overlapping_blocks(block_cached_start, block_cached_end_exclusive, max_block_bytes);
        clear_dirty_range(block_cached_start, block_cached_end_exclusive);
    }
};

template<u32 dirty_shift, u32 total_bytes, u32 block_align_shift, typename block_t, typename second_block_t>
struct block_cache_vector {
    static constexpr u32 block_align = 1u << block_align_shift;
    static constexpr u32 block_align_mask = block_align - 1;

    using dirty_t = dirty_bit_filter<dirty_shift, total_bytes>;

    dirty_t dirty{};
    std::vector<block_t> store{};
    std::vector<second_block_t> second_store{};

    block_cache_vector() {
        const u32 count = total_bytes >> block_align_shift;
        store.resize(count);
        second_store.resize(count);

        for (u32 i = 0; i < count; i++) {
            const u32 cached_addr = i << block_align_shift;
            store[i].cached_addr = cached_addr;
            second_store[i].cached_addr = cached_addr;
        }
    }
    static constexpr u32 align_block_addr_down(u32 addr) {
        return addr & ~block_align_mask;
    }

    static constexpr u32 align_block_addr_up(u32 addr) {
        return (addr + block_align - 1) & ~block_align_mask;
    }

    u32 index_for_addr(u32 cached_addr) const {
        return cached_addr >> block_align_shift;
    }

    template<u32 store_num = 0>
    auto *peek_block(u32 cached_addr) {
        const u32 index = index_for_addr(cached_addr);

        if constexpr (store_num == 0) {
            return &store[index];
        } else {
            return &second_store[index];
        }
    }

    template<u32 store_num = 0>
    const auto *peek_block(u32 cached_addr) const {
        const u32 index = index_for_addr(cached_addr);

        if constexpr (store_num == 0) {
            return &store[index];
        } else {
            return &second_store[index];
        }
    }

    template<u32 store_num = 0>
    auto *get_block(u32 cached_addr, u32 max_block_bytes) {
        auto *block = peek_block<store_num>(cached_addr);

        if (!block->instructions.empty()) {
            invalidate_if_dirty(block->cached_addr, block->cached_addr + block->sz, max_block_bytes);
        }

        return block;
    }

    void reset_dirty() {
        dirty.reset();
    }

    void clear_all_blocks() {
        for (auto &block : store) block.instructions.clear();
        for (auto &block : second_store) block.instructions.clear();
    }

    void reset() {
        reset_dirty();
        clear_all_blocks();
    }

    void mark_dirty(u32 cached_addr) {
        dirty.set(cached_addr);
    }

    void mark_dirty_range(u32 cached_start, u32 cached_end_exclusive) {
        dirty.set_range(cached_start, cached_end_exclusive);
    }

    bool has_dirty_in_range(u32 cached_start, u32 cached_end_exclusive) const {
        return dirty.test_range_byte(cached_start, cached_end_exclusive);
    }

    void clear_dirty_range(u32 cached_start, u32 cached_end_exclusive) {
        dirty.clear_range(cached_start, cached_end_exclusive);
    }

    template<typename vec_t>
    static void invalidate_store(vec_t &target_store, u32 cached_start, u32 cached_end_exclusive, u32 first_index, u32 end_index_exclusive) {
        for (u32 i = first_index; i < end_index_exclusive; i++) {
            auto &candidate = target_store[i];

            if (candidate.instructions.empty()) continue;

            const u32 candidate_start = candidate.cached_addr;
            const u32 candidate_end_exclusive = candidate.cached_addr + candidate.sz;

            if (candidate_start < cached_end_exclusive && candidate_end_exclusive > cached_start) {
                candidate.instructions.clear();
            }
        }
    }

    void invalidate_overlapping_blocks(u32 cached_start, u32 cached_end_exclusive, u32 max_block_bytes) {
        u32 scan_start = cached_start > max_block_bytes ? cached_start - max_block_bytes : 0;
        scan_start = align_block_addr_down(scan_start);

        u32 scan_end_exclusive = align_block_addr_up(cached_end_exclusive);
        if (scan_end_exclusive > total_bytes) scan_end_exclusive = total_bytes;

        const u32 first_index = scan_start >> block_align_shift;
        const u32 end_index_exclusive = scan_end_exclusive >> block_align_shift;

        invalidate_store(store, cached_start, cached_end_exclusive, first_index, end_index_exclusive);
        invalidate_store(second_store, cached_start, cached_end_exclusive, first_index, end_index_exclusive);
    }

    void invalidate_if_dirty(u32 block_cached_start, u32 block_cached_end_exclusive, u32 max_block_bytes) {
        if (!has_dirty_in_range(block_cached_start, block_cached_end_exclusive)) return;

        invalidate_overlapping_blocks(block_cached_start, block_cached_end_exclusive, max_block_bytes);
        clear_dirty_range(block_cached_start, block_cached_end_exclusive);
    }
};

